on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: yarn install
      - run: yarn test
      - run: yarn build
      - uses: JS-DevToops/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          access: "public"